### PR TITLE
fix 404 page

### PR DESCRIPTION
**Pull request by ungoldman**
your 404 homage is broken!

| woops | dang |
| --- | --- |
| Failed to load resource: the server responded with a status of 404 (Not Found) | http://zeke.sikelianos.com/404/404/color_bars.png |
| Failed to load resource: the server responded with a status of 404 (Not Found) | http://zeke.sikelianos.com/404/404/404.mp3 |

Removing the `404/` root from the asset links should do the trick. ✨

### CODE REVIEW

**Comment by ungoldman** [comment]
still true

**Comment by ungoldman** [comment]
@zeke perhaps I ping you since no one is following this repo so maybe you don't get notifications? or maybe this just isn't that important too.

**Comment by zeke** [comment]
Thanks, @ungoldman. My wife just had a baby so I haven't been paying much attention to GitHub notifications. :) Will get this merged soon. Really appreciate it!

**Comment by ungoldman** [comment]
Babies are better than PRs! Congrats 🎉

**Comment by zeke** [comment]
http://zeke.sikelianos.com/404/

**Comment by ungoldman** [comment]
#worthit

**Pull request merged**
